### PR TITLE
Fix: indirect group membership is also a list

### LINKED ISSUE #17: MemberofindirectGroup doesn's support multiple return values
I want to get indirect memberships of particular user via UserShow, e.g. if group `ipausers` is member in two other groups `hiddengroup` and `secondhiddengroup`.

Via CLI it works fine:

```
$ ipa user-show testuser
  User login: testuser
  First name: test
  Last name: test
  Home directory: /home/testuser
  Login shell: /bin/sh
  Principal name: testuser@EXAMPLE.COM
  Principal alias: testuser@EXAMPLE.COM
  Email address: testuser@example.com
  UID: 1377000025
  GID: 1377000025
  Account disabled: False
  Password: False
  Member of groups: ipausers
  Indirect Member of group: secondhiddengroup, hiddengroup     <---- two results
  Kerberos keys available: False
```

Via `freeipa.UserShow` I get an error from UserShow:

```
unexpected value for field MemberofindirectGroup: [secondhiddengroup hiddengroup]; expected at most one element 
```

```
$ ipa --version
VERSION: 4.6.8, API_VERSION: 2.237
$ rpm -qa | grep ipa
ipa-common-4.6.8-5.el7.centos.4.noarch
python2-ipaserver-4.6.8-5.el7.centos.4.noarch
python-ipaddress-1.0.16-2.el7.noarch
python-iniparse-0.4-9.el7.noarch
ipa-client-common-4.6.8-5.el7.centos.4.noarch
libipa_hbac-1.16.5-10.el7_9.7.x86_64
python-libipa_hbac-1.16.5-10.el7_9.7.x86_64
python2-ipaclient-4.6.8-5.el7.centos.4.noarch
ipa-client-4.6.8-5.el7.centos.4.x86_64
ipa-server-dns-4.6.8-5.el7.centos.4.noarch
sssd-ipa-1.16.5-10.el7_9.7.x86_64
ipa-server-common-4.6.8-5.el7.centos.4.noarch
python2-ipalib-4.6.8-5.el7.centos.4.noarch
ipa-server-4.6.8-5.el7.centos.4.x86_64
```

### PR DESCRIPTION
**Pull request by artem-sidorenko**
Fixes https://github.com/tehwalris/go-freeipa/issues/17

### CODE REVIEW

**Comment by riton** [comment]
I think this is a duplicate of #15 . Your patch handles the extra case `memberindirect_` and may be better than ours.

**Comment by riton** [comment]
I've encountered more special values that requires to be a list ...

I'm still not sure that our _patch_ covers all cases but this is a start https://github.com/ccin2p3/go-freeipa/blob/all_awaiting_patches_applied/gen/main.go#L177

**Comment by artem-sidorenko** [comment]
@riton indeed :) It would be nice to have a view of @tehwalris in order to know how we should ideally resolve this (and get it merged)

**Comment by tehwalris** [comment]
I've officially [stopped maintaining](https://github.com/tehwalris/go-freeipa#unmaintained) this repository. I'm sorry for not making that official sooner.

**Pull request closed without merging**
